### ISSUE TITLE
Using hash chaining to encode the dependency graph

### ISSUE THREAD

**Issue by edahlseng** [automerge/automerge#200] opened 2019-08-06 00:07 UTC
While looking through previous issues and pull requests, I’ve noticed a few mentions of a desire to move from vector clocks towards hash chaining for encoding the dependency graph (#27, #28, #31, #36). After reading through these issues and pull requests, there are a number of questions that come to mind:
* Is this still something that is desired? (If not, then the rest of the questions below become irrelevant!)
* Would it be okay if I started working towards adding this functionality?
    * It seems like adding hash-based integrity checking (#27) would be a good place to start, with full hash chaining to follow. Does this make sense?
    * Are there any backwards-compatibility concerns that would need to be kept in mind?
* What are the expected benefits of using hash chaining over vector clocks? A few potential benefits that jump to mind:
    * Dependency encoding becomes a fixed size for each change, rather than the `O(# of peers)` size that comes with vector clocks (though that’s only observed in the worst case, given the recent change to remove transitive dependencies from changes)
    * I _think_ we wouldn’t need to store the `states` object any more, instead we would only need to store a collection of each hash and its parent(s)
    * I _think_ we wouldn’t need to store `clock` or `deps` objects any more, instead we would only need to store a set of the most recently observed concurrent hashes
    * Any more?
* What are the expected drawbacks of using hash chaining over vector clocks?
  * One of the issues (#31) mentions that we would need to use a multi-round protocol to determine the latest common ancestor between peers
  * Any others?

**Comment by ept** [comment] 2019-08-14 11:15
Hi @edahlseng, I think this is still desirable, but I am not yet sure how exactly this feature should look like, and so it may take a few iterations before we are happy with it. You're welcome to explore the topic; I just say that to warn that the result might not be a quick "looks good to me, merge the PR" but might need some more deliberation.

In terms of efficiency, I think that hash chaining won't make a big difference. As you say, the vector clocks in changes already encode just the minimal dependencies (excluding transitive dependencies), so the size of encoding the dependencies with hashes would be roughly the same. And in terms of the data structures that need to be maintained, yes, we can remove some, but we also need to add a big map that allows changes to be looked up by their hash, which will probably have about the same size.

One thing that vector clocks give us is a synchronisation mechanism, as implemented e.g. by `Automerge.Connection`: that is, when two peers communicate, they need to figure out which changes they need to send to each other in order to converge. With hash chaining, this protocol would need to be replaced. I actually just recently designed a Byzantine fault tolerant protocol for performing this synchronisation, but I've not yet had time to write it up. I hope to do that soon.

**Comment by ept** [comment] 2019-08-14 11:19
Oh, and in terms of compatibility: changing from vector clocks to hash chaining would most likely be a breaking change (I imagine it would be difficult to enable synchronisation between a vector-clock-based client and a hash-chain-based client). While breaking changes will be necessary from time to time, I am keen to do them as rarely as possible, since they have such a big impact on deployments. So it might make sense to bundle this change together with other breaking changes (e.g. the new compressed binary data format I am working on) in a single release, so as to minimise its impact.

**Comment by edahlseng** [comment] 2019-08-14 21:54
Hi @ept, thanks for the responses! I'm excited to iterate on this with you, even if it takes a little back and forth. I'll put together an initial PR over the next week to get the ball rolling!

**Comment by ept** [comment] 2020-03-11 14:30
Picking up this thread again, as I've been thinking about hash chaining in the context of the new Automerge binary encoding format (in development on the `performance` branch).

I think that the best way forward is to keep the current system of tracking dependencies between changes (based on each change having an actorId and a sequence number), but to augment it with hashes to detect and fix data integrity problems. This allows us to continue using vector clocks for network protocols (e.g. in Automerge.Connection). Another advantage of the current system is that each actorId is typically used to generate many changes; therefore, the number of distinct actorIds is smaller than the number of changes; therefore, actorIds are repeated more often in a document's data; therefore (actorId, seq) pairs compress better than hashes, resulting in more efficient use of disk space and network bandwidth.

In the current system of change dependencies, each change with sequence number *n* by actor *A* (with *n*&nbsp;>&nbsp;1) implicitly depends on the change with sequence number *n*&nbsp;–&nbsp;1 by the same actor. Moreover, if *A* received changes from other actors between changes *n*&nbsp;–&nbsp;1 and *n*, then change *n* records the highest sequence number received from each other actor. Note that this is not a full vector clock, but only a minimal set of dependencies; any dependencies that can be reached transitively through another dependency do not need to be listed explicitly. This system is quite compact, even if there is a large-ish number of actorIds, since most of the time only a few actors are concurrently active at any one time.

The primary problem that hash-chaining needs to solve is to detect when some actor has created multiple different changes with the same actorId and the same sequence number. (See #234 for a recent example of an issue caused by reuse of sequence numbers.) To detect this, we extend the current system of dependencies with hashes. Whenever one change depends on another, we include the hash of the dependency in the dependent change. Thus, whenever there are multiple changes with the same (actorId, seq) pair, the hash removes the ambiguity about which change is the intended dependency.

This still leaves a problem: our list CRDT uses (actorId, counter) pairs — Lamport timestamps, to be precise — to uniquely identify list elements. (The counters are different from sequence numbers, since many list elements may be created in one change, resulting in many counter increments for a single seq.) If there are multiple changes with the same (actorId, seq), there may also be multiple list elements with the same ID. Any subsequent insertions or deletions that reference this ID would then be ambiguous.

One way of solving this would be to use (*hash*, counter) pairs instead of (actorId, counter) pairs to identify list elements, where *hash* is the hash of the change containing the operation that inserted this list element. This would make the list element IDs unambiguous, but it would make the encoding much less amenable to compression — all those hashes would take up a lot of space. And I've been working hard to reduce the storage overhead, especially for text, which requires such an ID per character!

Instead, I propose the following approach, which continues using actorIds (for better compression) most of the time. When we detect that there are multiple changes with the same (actorId, seq), and hence potentially ambiguous list element IDs, we keep track of the subsequent dependency graph. A change whose transitive dependency set includes only one of the changes with conflicting sequence numbers can continue using the usual (actorId, counter) to refer to list element IDs, and we can use the dependency graph to unambiguously figure out which of the list elements it is referring to. Only for changes whose dependencies include both of the conflicting changes, we switch to using hashes instead of actorIds for list element IDs, in order to make them unambiguous.

This approach means that we incur the additional storage cost of using hashes instead of actorIds only in the case when multiple changes with the same (actorId, seq) have been created; in the common case, when there are no such conflicts, we maximise the compression we can achieve.

I think that this approach ensures that CRDT convergence is always guaranteed, even in the case when sequence numbering fails. More strongly, I think that it ensures that users who are correctly following the protocol always converge, even if some of the collaborators are arbitrarily malicious or buggy (i.e. even if there are Byzantine faults). This would be a very nice property to achieve — I am not aware of any existing CRDT that is so robust against Byzantine faults.

Feedback on the above proposal is very welcome!

**Comment by savaki** [comment] 2020-03-11 17:49
If you only use actor ids when you detect there are multiple changes, doesn't this imply that each merge has a time limit after which it must be accepted.

For example, given original document A and two child documents B and C.  Isn't it possible that any existing element within A could be a point of conflict between B and C?  When would you decide when to store the hash and when would you decide when to store (actorId, seq)?

For my own mental model, I've been using git as an analogy.  If operations are the equivalent to changes in the document, then deps (or weave as I've also heard it called) becomes the commit to which you can associate a hash.

**Comment by savaki** [comment] 2020-03-11 18:13
I reread the proposal and realized I must have misunderstood it the first time around.

As I understand it, there are two separate problems being solved.  
* How to detect reused (actorId, seq) pairs #234 
* The second is about potentially ambiguous list elements ids.

For the first issue, why not just detect reuse on load?  In go, I'm able to load the 260k performance doc in about 2.3s reading operation by operation, https://github.com/savaki/automerge-benchmark.  And I think there's still significant room to bring that time down.

If the concern is about corruption of the operation log, what about using a more git like system?  If we think operations as edits to a file within a file, then the dep tree can thought of as the change list.  So rather than attaching a hash to each operation, which I agree would bloat the size of the doc, why not hash the dep tree periodically?  The hash chain would be preserved and the cost of storing the hash would be greatly reduced.

I'm not sure I understand the problem that's being addressed by the second issue.

**Comment by ept** [comment] 2020-03-11 21:22
@savaki The first problem we need to solve is two nodes thinking that they are in the same state, when in fact they are inconsistent. Say for example that A sends change X with sequence number 1 to B, and A also sends change Y with sequence number 1 to C. Now, when B and C communicate and exchange vector clocks, they think they are in sync because they both have sequence number 1 from A; they do not detect that X and Y are different. What the hashes allow is for B and C to exchange hashes, and thus detect if there are any inconsistencies between their views of the change history.

**Comment by savaki** [comment] 2020-03-11 22:41
Is this the case where you the two documents, B and C, have no common ancestor?  Or is this the byzantine example where A is malicious and intentionally sends B and C different data?

**Comment by ept** [comment] 2020-03-12 09:58
This is the Byzantine case where A is malicious (or buggy).

**Comment by ept** [comment] 2020-12-02 16:27
Hash chaining of Automerge changes is implemented as part of the new binary format #253. Implications for networking layers are discussed in #290. I'm going to close this issue and leave further discussion on those issues.

**Closed by ept** 2020-12-02 16:27 UTC
