### ISSUE TITLE
undo of change fails when moving object from a sub object array

### ISSUE THREAD

**Issue by virtualcodewarrior** [automerge/automerge#247] opened 2020-04-03 21:11 UTC
Hi,
According to the documentation, the undo just executes the steps in reverse.

But if I do the following, it will throw an exception at the undo step only. While it allows the change to happen. 

```
let doc1 = Automerge.from({ objects: [
		{ name: '7', objects: [{ name: '7-1' }, { name: '7-2' }, { name: '7-3' }, { name: '7-4' }] },
		{ name: '1' },
		{ name: '2' },
		{ name: '3' },
		{ name: '4' },
		{ name: '5' },
		{ name: '6' },
	] });

// this takes the items of object 7 and moves them to the root array
doc1 = Automerge.change(doc1, 'ungroup', (doc) => {
       // take out object 1
	const [object] = doc.objects.splice(0, 1);
        // move child objects to the root array
	while (object.objects.length) {
		doc.objects.insertAt(ungroupIndex, object.objects.pop());
	}
});

// undo the last step
doc1 = Automerge.undo(doc1);
```

Exception thrown on undo
```
apply_patch.js:55 Uncaught RangeError: Object 09820b13-15e9-4990-90c5-4cbe72217623 has multiple parents
    at updateInbound (apply_patch.js:55)
    at updateListObject (apply_patch.js:273)
    at applyDiffs (apply_patch.js:435)
    at applyPatchToDoc (index.js:138)
    at makeChange (index.js:114)
    at Object.undo (index.js:401)
    at Object.undo (automerge.js:50)
    at index.js:92
updateInbound @ apply_patch.js:55
updateListObject @ apply_patch.js:273
applyDiffs @ apply_patch.js:435
applyPatchToDoc @ index.js:138
makeChange @ index.js:114
undo @ index.js:401
undo @ automerge.js:49
(anonymous) @ index.js:92
```

Is it expected that undo would fail on this or is there actually a problem either with my code or with the undo implementation ?

**Comment by ept** [comment] 2020-04-06 17:28
Hi @virtualcodewarrior, thank you for reporting this. Your code is fine, this is a bug in Automerge. I will look into it.

**Comment by ept** [comment] 2020-04-20 19:58
Minimal test case to reproduce:

```js
it('should undo object moves', () => {
  let s1 = Automerge.from({a: {name: 'A', child: {name: 'B'}}})
  s1 = Automerge.change(s1, doc => { let b = doc.a.child; delete doc.a.child; doc.b = b })
  assert.deepStrictEqual(s1, {a: {name: 'A'}, b: {name: 'B'}})
  s1 = Automerge.undo(s1) // this line throws an exception
  assert.deepStrictEqual(s1, {a: {name: 'A', child: {name: 'B'}}})
})
```

I think the problem is the way the undo history is constructed operation by operation. When the object B is moved, the change contains two operations:

```js
{"action": "del", "key": "child", "obj": objA}, // unlinking object B from A
{"action": "link", "key": "b", "obj": ROOT_ID, "value": objB} // linking B into the root
```

The undo history for this change is constructed operation by operation:

```js
{"action": "link", "obj": objA, "key": "child", "value": objB},
{"action": "del", "obj": ROOT_ID, "key": "b"}
```

The "link" is the inverse of "del", and vice versa. Now, when we apply the undo, the resulting patch also first links B into A, and then unlinks B from the root. The first of these fails when applying the patch: at that point, B's parent is still the root, and so we can't also set B's parent to A.

To fix this, either undo history generation or patch generation will need to reverse the order in which the undone changes are applied. Perhaps the algorithm should operate on explicit move operations, rather than the current delete-and-link approach.

**Comment by ept** [comment] 2021-02-11 16:32
This issue relates to the Automerge 0.x release series. In 1.x we have removed the undo feature because it was poorly designed (including issues such as this), so I will close this issue. When we bring back undo, we should do it using proper move operations, which will avoid the problem described here.

**Closed by ept** 2021-02-11 16:32 UTC
