### ISSUE TITLE
TypeError: Cannot read property 'canUndo' of undefined

### ISSUE THREAD

**Issue by mccoysc** [automerge/automerge#132] opened 2018-11-22 01:59 UTC
var autoMerge = require('automerge')
var doc1 = autoMerge.init();
var doc2 = autoMerge.init();
doc1 = autoMerge.change(doc1, "add an empty array a", function (doc) {
    doc.a = []
});
doc2 = autoMerge.change(doc2, "add and empty object a", function (doc) {
    doc.a = {}
});

var changes1 = autoMerge.getChanges(autoMerge.init(), doc1);
var changes2 = autoMerge.getChanges(autoMerge.init(), doc2);
doc1 = autoMerge.applyChanges(doc1, changes2);
doc2 = autoMerge.applyChanges(doc2, changes1);
autoMerge.canUndo(doc1) 
TypeError: Cannot read property 'canUndo' of undefined

**Comment by ept** [comment] 2018-12-06 21:18
Closing this issue as I cannot reproduce it.

**Closed by ept** 2018-12-06 21:18 UTC
