### ISSUE TITLE
Conflict is not recognised when there are multiple key assignments

### ISSUE THREAD

**Issue by fo-fo** [automerge/automerge#506] opened 2022-08-19 05:06 UTC
I would like to know what causes the difference in behavior in the following two tests. The only difference between the two tests is that the 2nd test initializes the docs with an extraneous `myObject` object, which is not used or referenced after initialization. Why does the presence of that field/object affect how the `myArray` field behaves?

Also, how in general is it possible that after merging all changes from both sides `myArray` didn't wind up in the same state in both docs in the 2nd test?

 ```typescript
 import Automerge from "automerge";

test("conflict test 1", () => {
  type Type = {
    myArray: string[];
  };
  const doc1_v1 = Automerge.from<Type>({ myArray: [] });
  const doc2_v1 = Automerge.from<Type>({ myArray: [] });
  const doc1_v2 = Automerge.change(doc1_v1, (doc) => {
    doc.myArray.push("item1");
  });
  const doc2_v2 = Automerge.change(doc2_v1, (doc) => {
    doc.myArray.push("item2");
  });
  const doc1_v3 = Automerge.merge(
    Automerge.clone(doc1_v2),
    Automerge.clone(doc2_v2),
  );
  const doc2_v3 = Automerge.merge(
    Automerge.clone(doc2_v2),
    Automerge.clone(doc1_v2),
  );

  // Both docs are
  //  { myArray: [ 'item1' ] }, OR
  //  { myArray: [ 'item2' ] }, as expected.
  console.log(doc1_v3);
  console.log(doc2_v3);

  // Conflicts are present in both docs, as expected.
  console.log(Automerge.getConflicts(doc1_v3, "myArray"));
  console.log(Automerge.getConflicts(doc2_v3, "myArray"));
});

test("conflict test 2", () => {
  type Type = {
    myArray: string[];
    myObject: Record<string, string>;
  };
  const doc1_v1 = Automerge.from<Type>({ myArray: [], myObject: {} });
  const doc2_v1 = Automerge.from<Type>({ myArray: [], myObject: {} });
  const doc1_v2 = Automerge.change(doc1_v1, (doc) => {
    doc.myArray.push("item1");
  });
  const doc2_v2 = Automerge.change(doc2_v1, (doc) => {
    doc.myArray.push("item2");
  });
  const doc1_v3 = Automerge.merge(
    Automerge.clone(doc1_v2),
    Automerge.clone(doc2_v2),
  );
  const doc2_v3 = Automerge.merge(
    Automerge.clone(doc2_v2),
    Automerge.clone(doc1_v2),
  );

  // doc1 is
  //  { myArray: [ 'item1' ], myObject: {} },
  // doc2 is
  //  { myArray: [ 'item2' ], myObject: {} },
  // or the other way around, depending on actor IDs.
  console.log(doc1_v3);
  console.log(doc2_v3);

  // One of these returns undefined, the other returns the expected conflict (depends on actor IDs).
  console.log(Automerge.getConflicts(doc1_v3, "myArray"));
  console.log(Automerge.getConflicts(doc2_v3, "myArray"));
});
```

**Comment by ept** [comment] 2022-08-30 16:13
This is a bug; thank you for the nice test case. The conflict ought to show up regardless in which order the documents are merged. I found that to reproduce the bug, you don't even need nested objects — the following is sufficient to reproduce the issue:

```js
const s1 = Automerge.change(Automerge.init('22'), doc => { doc.x = 1 })
const s2 = Automerge.change(Automerge.init('11'), doc => { doc.x = 2; doc.y = 3 })
const m1 = Automerge.merge(s1, s2)
console.log(Automerge.getConflicts(m1, 'x'))
```

Internal details follow. The problem occurs when the first argument to `merge()` has the greater actorId. In this case, `mergeDocChangeOps` first applies the change op (the assignment to `x` from the second argument to `merge`), then loads the next change op (the assignment to `y` from the second argument to `merge`) while `docOp` is still the assignment to `x` from the first argument to `merge`. At this point, `keyMatches`, `listElemMatches`, and `foundListElem` are all `false`, and so we don't take the branch at backend/new.js:1169, and in particular we never reach the call to `updatePatchProperty` at backend/new.js:1203. Hence, `docOp` is not added to the patch and so it doesn't show up in the conflict.

The bug only shows up if the second argument to `merge` contains another op which is loaded into `changeOp`; if there is no such op (e.g. if we remove the assignment to `y` in the example above), `changeOp` still contains the previous op, so `keyMatches == true`, and therefore the patch is updated as it should be.

I'm not sure right now how to best fix this bug. Given that we're moving towards making the Rust/Wasm implementation of Automerge the primary one, the most important thing is to ensure this bug doesn't occur there.

**Comment by ept** [comment] 2022-08-30 16:18
I pushed a failing test case for this to the [conflict-test](https://github.com/automerge/automerge/compare/conflict-test) branch (9857eeb404ecaefba86b798bcaf66ebee18a8acb)

**Comment by alexjg** [comment] 2022-09-12 17:22
FWIW the failing test passes using the WASM backend.

**Comment by ept** [comment] 2022-09-12 17:52
Great, then I think we don't need to fix this bug in the JS implementation since it's going to be deprecated anyway.

**Closed by ept** 2022-09-12 17:52 UTC

**Comment by fo-fo** [comment] 2022-09-13 02:00
How straightforward is it to migrate from the JS implementation to using the WASM backend?

**Comment by pvh** [comment] 2022-09-13 02:39
It should be almost 100% compatible, aside from requiring waiting for the `automerge-wasm` blob to load (browsers block synchronous WASM loading). We're currently working through a last few things before an offical release (like improving docs) but you can try https://github.com/automerge/automerge-rs/tree/main/automerge-js in the meantime and pass along any feedback if you run into problems.

**Comment by pvh** [comment] 2022-09-13 02:40
(You should be able to `yarn add automerge-wasm automerge-js`. The latter will become `automerge` as part of the change-over process.)

**Comment by fo-fo** [comment] 2022-09-13 02:56
Thanks! I'll try it out at some point and see if any issues arise.
