### ISSUE TITLE
table error

### ISSUE THREAD

**Issue by mccoysc** [automerge/automerge#141] opened 2018-12-09 06:26 UTC
first,i create a new doc and doc.table=new Automerge.Table(cols);
and make some change like doc.add.
and save every changes to local.
and then exit my process.

and re-run the same code again(also apply the saved changes to the new doc), and then when run to code "doc.table.add" and return to Automerge.change callback, an error like the following:

op_set.js:185 Uncaught Error: Modification of unknown object 0c148164-bfd2-469a-b8ce-25e9694e843d
    at applyAssign (op_set.js:185)
    at applyOps (op_set.js:237)
    at applyChange (op_set.js:260)
    at applyQueuedOps (op_set.js:278)
    at Object.addChange (op_set.js:325)
    at apply (index.js:148)
    at Object.applyLocalChange (index.js:186)
    at makeChange (index.js:99)
    at Object.change (index.js:266)
    at Object.change (automerge.js:26)

**Comment by mccoysc** [comment] 2018-12-09 06:31
@pvh

**Comment by ept** [comment] 2018-12-13 13:32
@mccoysc I can't reproduce this error from the verbal description. Could you please provide a complete code sample that produces the error? It sounds similar to your issue #136, which was due to incorrect use of the APIs.

I am worried by your statement "re-run the same code again (also apply the saved changes to the new doc)". Note that when you load saved changes, you don't need to re-run the code that created the document, because all the details on how to create the document are included in the saved changes. If you do re-run the code as well as loading changes, you are effectively making the changes twice, which is likely to lead to clashes.

**Comment by ept** [comment] 2019-02-04 15:57
Closing this issue because it can't be reproduced. Please re-open if you can provide more detail.

**Closed by ept** 2019-02-04 15:57 UTC
