### ISSUE TITLE
assignment merges

### ISSUE THREAD

**Issue by choxi** [automerge/automerge#19] opened 2017-05-19 01:31 UTC
Adam found a bug where assignments were getting clobbered on merges, I figured out that it was happening because on assignment updates I was resetting the entire `assigned` object instead of the specific prop:

```javascript
  updateAssignments(state, action) {
    let cardIndex = this._findIndex(state.cards, (c) => c.id === action.cardId)
    return Tesseract.set(state.cards[cardIndex], "assigned", action.assigned)
  }
```

So I tried:

```javascript
  updateAssignments(state, action) {
    let cardIndex = this._findIndex(state.cards, (c) => c.id === action.cardId)

    // cards don't have an "assigned" prop by default,
    // we have to set it if it doesn't already exist
    if(!state.cards[cardIndex].assigned)
      state = Tesseract.set(state.cards[cardIndex], "assigned", {})

    // make the update more granular so we don't clobber the entire "assigned" object
    return Tesseract.set(state.cards[cardIndex].assigned, action.person, action.isAssigned)
  }
```

However, this doesn't work either because now we're clobbering the "assigned" object when we initialize it in the `if` expression. I finally got it to work by making sure every card has the "assigned" prop when it's created (in the seed data or when a user creates a card). You can see the full diff [here](https://github.com/inkandswitch/trellis/commit/8a00afcf5b7d5ed9bbc602f9b0a7cc5ae906c87d).

This works in our use case because no one's using the app so it's easy enough to change how we initialize the data, but if we were using Trellis in production I'd have to write a migration to add an empty "assigned" property to every card and make sure all future cards have it by default. I'm not sure if that would even work because the migration itself could end up clobbering some users' assignment props. Is there a better way to handle this that I haven't thought of?

**Comment by ept** [comment] 2019-05-06 10:10
Closing this as the issue is discussed in detail in #4.

**Closed by ept** 2019-05-06 10:10 UTC
